### ISSUE TITLE
html/markdown content in collection description?

### ISSUE THREAD

**Issue by Ambrosiani** [tainacan/tainacan#453] opened 2020-11-16 08:45 UTC
**Context and motivation**

I've hardcoded a "contribute" button into the collection header but would prefer to control this from the collection settings.

**Alternative solutions**

Maybe let the description field have markdown support, or load it from a gutenberg block, or add another field "call to action button"

**Additional context**

Screenshot of existing description + hardcoded addition. Url: https://monument.kvinnohistoriska.se/kvinnans-sak/

<img width="783" alt="Skärmavbild 2020-11-16 kl  09 39 58" src="https://user-images.githubusercontent.com/2394405/99230933-36cd7180-27f0-11eb-94f0-36ccb39ecf9b.png">

<img width="1655" alt="Skärmavbild 2020-11-16 kl  09 43 59" src="https://user-images.githubusercontent.com/2394405/99230986-48167e00-27f0-11eb-99d4-788b891a770c.png">

<img width="1053" alt="Skärmavbild 2020-11-16 kl  09 44 30" src="https://user-images.githubusercontent.com/2394405/99231029-582e5d80-27f0-11eb-93ff-8721a66d57fe.png">

**Comment by mateuswetah** [comment] 2020-11-16 12:21
Hi @Ambrosiani!

Hey, that theme looks really cool! And yes, I also find this an important issue. We've been too limited by themes implementation of the Collection description. 

You should know that you can also put some HTML content on your Collection description, but this is actually a security [issue](https://github.com/tainacan/tainacan/issues/447) and we're working to prevent it very, very soon! The same goes for Term pages. In fact we've been discussing the Markdown vs Block solution last week... it might take us a while to implement due to a large list of features that we have planned so far, but just to let clear, you can have a temporary solution:

1. Create a page using Gutenberg blocks as you wish and use the "Faceted Items Lists" block to render your Collection;
2. Set that page as "Cover page" of your Collection, in the Collection settings.

Obviously that is far from ideal as you would have to do for every collection that you have. Also, setting a cover page is not possible in Terms items list, but we recently opened an issue for that too (https://github.com/tainacan/tainacan/issues/448).

I'll keep this open so we can discuss a solution and prioritize it.

**Comment by Ambrosiani** [comment] 2020-11-16 12:26
@mateuswetah hi, thanks for the suggestions! Using a separate cover page seems like the easiest way for now – we're only dealing with one public collection at the moment.

**Comment by mateuswetah** [comment] 2021-07-13 17:44
Marking this as related to #582!

**Comment by mateuswetah** [comment] 2024-04-02 14:59
Closing as duplicate of #582. Once we define the wysiwyg component we should be able to implement this in the collection description.

**Closed by mateuswetah** 2024-04-02 14:59 UTC
