### ISSUE TITLE
All Items Randomly Disappear

### ISSUE THREAD

**Issue by joshtillman** [tainacan/tainacan#314] opened 2019-10-08 16:57 UTC
**Bug description**

What is happening?

Randomly, all items (107) disappear on the front-end but are still there in the back-end. I'm using Tainacan with the Tainacan theme.

**How to reproduce such bug**

1. Go to https://fakenewstoolkit.sdsu.edu
2. The items will not display and instead just say "No item was found." This step is random. Sometimes it works as intended and sometimes not (see screenshots).

**Expected behavior**

What did you expect to happen?

I expect it to work all the time.

**Screenshots**

When it is working:
![working](https://user-images.githubusercontent.com/18602820/66415711-0db59d00-e9b1-11e9-900c-14cc30ca61eb.jpg)

When it is not working:
![not-working](https://user-images.githubusercontent.com/18602820/66415712-0db59d00-e9b1-11e9-950f-cb521411cf82.jpg)

**Desktop (please complete the following information):**

 - OS: [e.g. iOS] Windows 10
 - Browser [e.g. chrome, safari] Chrome 77.0.3865.90, Firefox 69.0.2, IE 11

**Comment by joshtillman** [comment] 2019-10-08 17:00
To add a little more: I have to edit an item in the back-end to get the items to reappear on the front-end. This happens roughly every 24 hours. Very annoying.

**Comment by mateuswetah** [comment] 2019-10-08 17:04
Hi @joshtillman, I am trying to reproduce it here, but it's not happening. Let's try to dig a little more. Could you open the developer tools of your browser (usually CTRL + SHIFT + I) and tell us if you see anything Red on the Network tab? Don't worry about your data, as you said it is safe, this seems to be frontend issue when loading the items.

**Comment by joshtillman** [comment] 2019-10-08 17:13
There are 3 but this is based on when it is working:
![network-dev-tools](https://user-images.githubusercontent.com/18602820/66417046-06dc5980-e9b4-11e9-8a2d-316573a97a7e.jpg)

**Comment by mateuswetah** [comment] 2019-10-08 17:17
Ok, that `canceled` is fine, it is there to avoid repetitive requests. The `/me` should be red if at that time you were not logged.

One thing that sometimes happens to me, although more often on the admin side, is leaving my browser open for a long time or reopen it after some time and having my credentials expired. This way the request would return me 401. Usually I just try to access and log in WordPress panel again (the browser might require a refresh as the view might be rendered, cashed from before). Again, this is a supposition, let's see if it's the case.

**Comment by joshtillman** [comment] 2019-10-09 16:46
I checked this morning and it's not working again. You should be able to see it: https://fakenewstoolkit.sdsu.edu

If not, here's the dev tools network:
![network-dev-tools-2](https://user-images.githubusercontent.com/18602820/66502138-90099400-ea79-11e9-9aa8-101172c88b6b.jpg)

**Comment by leogermani** [comment] 2019-10-09 17:26
Hi @joshtillman,

We understood the problem but it is no clear what is causing it. 

Are you using any cache plugins?

**Comment by joshtillman** [comment] 2019-10-09 17:55
Yes, Hummingbird from WPMU DEV. This is also on multisite if that matters.

**Comment by leogermani** [comment] 2019-10-09 18:09
Ok, It's probably something related to caching. We have to test it and improve a bit the way we handle the x-wp-nonce header... We will dig into it.

Meanwhile, if it is possible, can you deactivate the cache and confirm it solves the problem?

**Comment by joshtillman** [comment] 2019-10-11 15:28
The problem occurred again this morning and when I reset the cache through Hummingbird, it fixed the problem.

**Comment by leogermani** [comment] 2019-10-21 14:00
Hi @joshtillman 

Replying to let you know we acknowledge this problem and we are evaluating the best way to solve it.

I've been reading about this and it is a common problem with some plugins that use "nonce" verification to protect some actions in their sites. There are some useful references:

* https://medium.com/myatus/wordpress-caching-and-nonce-lifespan-bb357d984da9
* https://joshpress.net/wordpress-nonces-and-wordpress-caching/

One solution they suggest is to decrease the lifespan of the cache to less than 12 hours (which is the lifespan of a nonce). 

I think that is the best solution for now. How long is your cache set to live?

**Comment by joshtillman** [comment] 2019-10-21 17:40
Our server micro-cache only caches a page for a few seconds. The Hummingbird plugin only caches CSS, JS, Images, and media files (1-2 months). This does not cause a problem with any of our other plugins, only yours.

**Comment by leogermani** [comment] 2019-10-23 12:22
I've accessed the website just now and I can see this comment at the end:

```
<!-- Hummingbird cache file was created in 0.12832999229431 seconds, on 22-10-19 12:09:27 -->
```
Apparently, Hummingbird is caching the HTML and not only static files. And it's doing thi for longer than 12 hours.

Can you double-check?

**Comment by leogermani** [comment] 2019-11-08 13:49
Hi @joshtillman ,

It seems that everything is fine now! I've been checking the site every now and then and it's always working (also noticed that the Hummingbird message is gone)

I've added a note about this issue in our wiki:

https://tainacan.github.io/tainacan-wiki//#/optimization?id=cache

So I'm closing this issue for now as I don't think there is much to do on our side. 

cheers

**Closed by leogermani** 2019-11-08 13:49 UTC
Labels: bug
