### ISSUE TITLE
Option to enable comments on an item not working

### ISSUE THREAD

**Issue by lwdias** [tainacan/tainacan#460] opened 2020-11-23 21:25 UTC
**Bug description**

When I access an item in a collection and mark it to allow comments and click update, the system sends me back to the item's details page and the comments option appears as not allowed.

**How to reproduce such bug**

1. Click on a collection
2. Click on any item
3. Click edit item
4. Check to allow comments
5. Click Update
6. In the item details screen, the comment remains "not allowed"

**Expected behavior**
The comments should be allowed when I select to allow

**Screenshots**
Edit screen: http://srv36.teste.website/~lwdias/comments_1.png
Details of the item: http://srv36.teste.website/~lwdias/comments_2.png

**Versions**
Tainacan: 0.17RC
Wordpress: 5.5.3
PHP: 7.0

**Comment by mateuswetah** [comment] 2020-11-24 16:56
Hi @lwdias!

So far I wasn't able to reproduce this error... but it really seems that something is wrong. Just to know, is your collection also enabled for comments on the items (there is a high level setting for that in the collection edition form).

And also, if you check the console errors, can you identify anything related to it when checking that switch and then updating the item page?

**Comment by mateuswetah** [comment] 2020-11-26 12:28
One other thing that you could test: are you able to switch the item visibility from `public` to `private`?

**Comment by mateuswetah** [comment] 2021-02-11 12:28
@lwdias have you tried this recently?

**Comment by mateuswetah** [comment] 2021-07-13 17:59
Closing this due to no feedback. If there anyone can reproduce it again, feel free to open a new issue :)

**Closed by mateuswetah** 2021-07-13 17:59 UTC
Labels: bug
